version: '3'

services:

#database
  mysqldb:
    image: mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - docker-compose-project

#frontend
  trainee_frontend:
    depends_on:
      - trainee_backend
    build:
      context: ./trainee_frontend
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - 8888:80
    networks:
      - docker-compose-project

#backend
  trainee_backend:
    depends_on:
      - mysqldb
    build: ./trainee_backend
    env_file: ./.env
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    ports:
      - 6868:8080
    networks:
      - docker-compose-project


networks:
  docker-compose-project:


  


