version: '3'

services:

#database
  mysqldb:
    image: mysql
   
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - docker-compose-project

#frontend
  trainee_frontend:
    depends_on:
      - trainee_backend
    build:
      context: ./trainee_frontend
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - 5001:80
    networks:
      - docker-compose-project

#backend
  trainee_backend:
    depends_on:
      - mysqldb
    build: ./trainee_backend
 
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    ports:
      - 5000:8080
    networks:
      - docker-compose-project


networks:
  docker-compose-project:


  


